name: Execute tests on coldbox modules
on:
    workflow_dispatch:
      inputs:
        boxlang_commit:
          type: string
          required: true
          description: Last commit in Boxlang's GitHub repository that triggered this workflow

permissions:
  actions: write
  contents: read
  checks: write

jobs:
    snapshot-convention:
        secrets: inherit
        uses: ./.github/workflows/triggerColdBoxModulesSnapshotConvention.yml
        with:
            boxlang_commit: ${{ github.event.inputs.boxlang_commit }}

    ci-convention:
        secrets: inherit
        uses: ./.github/workflows/triggerColdBoxModulesCIConvention.yml
        with:
            boxlang_commit: ${{ github.event.inputs.boxlang_commit }}