name: Trigger ColdBox Modules Tests
on:
    workflow_dispatch:
    push:

permissions:
  actions: write
  contents: read

env:
  GITHUB_ORGANIZATION: coldbox-modules

jobs:
    trigger:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                repositories: ["cbSwagger", "cbdebugger"]
            fail-fast: false
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Trigger ColdBox Module
              uses: convictional/trigger-workflow-and-wait@v1.6.5
              with:
                owner: ${{ env.GITHUB_ORGANIZATION }}
                repo: ${{ matrix.repositories }}
                github_token: ${{ secrets.TOKEN }}
                workflow_file_name: snapshot.yml
                ref: development
                wait_interval: 120
                propagate_failure: false
                trigger_workflow: true
                wait_workflow: true
              id: trigger

            - name: Download Tests
              uses: actions/download-artifact@v4
              with:
                pattern: '*boxlang*'
                path: ${{ matrix.repositories }}-tests
                github-token: ${{ secrets.TOKEN }}
                repository: ${{ env.GITHUB_ORGANIZATION }}/${{ matrix.repositories }}
                run-id: ${{ steps.trigger.outputs.workflow_id }}

            - name: What is in download folder
              run: |
                pwd
                ls -la
                tree .

            - name: Publish Test Results
              uses: EnricoMi/publish-unit-test-result-action@v2
              if: always()
              with:
                junit_files: ${{ matrix.repositories }}-tests/*.xml
                check_name: "${{ matrix.repositories }}-${{ matrix.cfengine }}-ColdBox_${{ matrix.coldboxVersion }}"

            - name: Upload Test Results to Artifacts
              if: always()
              uses: actions/upload-artifact@v3
              with:
                name: test-results-${{ matrix.cfengine }}-${{ matrix.coldboxVersion }}
                path: |
                  ${{ matrix.repositories }}-tests/*
