name: Trigger ColdBox Modules Tests
on:
    workflow_dispatch:
    push:

permissions:
  actions: write
  contents: read

env:
  GITHUB_ORGANIZATION: coldbox-modules

jobs:
    trigger:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                repositories: ["cbSwagger", "cbdebugger"]
        steps:
            - name: Trigger ColdBox Module
              uses: convictional/trigger-workflow-and-wait@v1.6.5
              with:
                owner: ${{ env.GITHUB_ORGANIZATION }}
                repo: ${{ matrix.repositories }}
                github_token: ${{ secrets.TOKEN }}
                workflow_file_name: snapshot.yml
                ref: development
                wait_interval: 120
                propagate_failure: false
                trigger_workflow: true
                wait_workflow: true
              id: trigger
            
            - name: Lookup for tests results
              uses: actions/download-artifact@v4
              with:
                pattern: test-results-boxlang*
                path: ${{ matrix.repositories }}-tests
                github-token: ${{ secrets.TOKEN }}
                repository: ${{ env.GITHUB_ORGANIZATION }}/${{ matrix.repositories }}
                run-id: ${{ steps.trigger.outputs.workflow_id }}
            
            - name: Unzip test results
              run: |
                  ls -la
